"""'init'

Revision ID: 5a5f6dd908d2
Revises: 
Create Date: 2023-09-07 16:42:42.765948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5f6dd908d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('major', sa.String(length=10), nullable=True),
    sa.Column('minor', sa.String(length=10), nullable=True),
    sa.Column('patch', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family', 'major', 'minor', 'patch', name='unique_browser')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family', 'brand', 'model', name='unique_device')
    )
    op.create_table('os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('major', sa.String(length=10), nullable=True),
    sa.Column('minor', sa.String(length=10), nullable=True),
    sa.Column('patch', sa.String(length=10), nullable=True),
    sa.Column('patch_minor', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family', 'major', 'minor', 'patch', 'patch_minor', name='unique_os')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.Enum('client', 'developer', 'bot', 'moderator', 'admin', 'superuser', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('device_browser_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('browser_id', sa.Integer(), nullable=True),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['browser_id'], ['browser.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['os.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'browser_id', 'os_id', name='unique_device_browser_os')
    )
    op.create_table('dialog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_browser_os_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_browser_os_id'], ['device_browser_os.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_browser_os_id'),
    sa.UniqueConstraint('user_id', 'device_browser_os_id', name='unique_client')
    )
    op.create_table('dialog_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialog.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_readers',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_readers')
    op.drop_table('message')
    op.drop_table('dialog_participant')
    op.drop_table('client')
    op.drop_table('dialog')
    op.drop_table('device_browser_os')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('os')
    op.drop_table('device')
    op.drop_table('browser')
    # ### end Alembic commands ###
