version: "3.9"

services:
  auth:
    container_name: auth
    build:
      context: ./apps/server/auth
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    depends_on:
      - db
    restart: always
    entrypoint: [ "uvicorn", "server_auth.main:app", "--host", "${AUTH_HOST}", "--port", "${AUTH_PORT}" ]
    networks:
      net:
        aliases:
          - ${AUTH_HOST}
  db:
    container_name: db
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    networks:
      net:
        aliases:
          - ${POSTGRES_HOST}
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
    networks:
      net:
        aliases:
          - ${REDIS_HOST}
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      net:
        aliases:
          - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      net:
        aliases:
          - prometheus
volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${STORE_DIR}/prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${STORE_DIR}/grafana_data
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${STORE_DIR}/data

networks:
  net:
    driver: bridge
