[tool.nx]
autoActivate = true

[tool.poetry]
name = "botswork"
version = "1.0.0"
description = ""
authors = [ ]
license = "Proprietary"
readme = "README.md"

  [tool.poetry.dependencies]
  python = "~=3.11.5"
  fastapi = "^0.103.1"
  uvicorn = {extras = ["standard"], version = "^0.23.2"}
  psycopg2-binary = "^2.9.7"
  asyncpg = "^0.28.0"
  sqlalchemy = "^2.0.20"
  alembic = "^1.12.0"
  bcrypt = "^4.0.1"
  fastapi-another-jwt-auth = {git = "https://github.com/GlitchCorp/fastapi-another-jwt-auth", rev = "refs/pull/20/merge"}
  passlib = "^1.7.4"
  python-dotenv = "^1.0.0"
  asyncio = "^3.4.3"

    [tool.poetry.dependencies.py-db]
    path = "libs/py/db"
    develop = true

    [tool.poetry.dependencies.server-auth]
    path = "apps/server/auth"
    develop = true

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.2"
flake8 = "6.0.0"
pytest = "7.3.1"
pytest-sugar = "0.9.7"
pytest-cov = "4.1.0"
pytest-html = "3.2.0"

[build-system]
requires = [ "poetry-core==1.1.0" ]
build-backend = "poetry.core.masonry.api"
