global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: [ ]
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: 'sso'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - sso:8000
  - job_name: 'nginx_status'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - nginx_exporter:9113
  - job_name: 'postgresql'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - postgresql_exporter:9187
  - job_name: 'redis'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - redis_exporter:9121
  - job_name: 'io'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - nginx:2000
          - nginx:2001
          - nginx:2002
          - nginx:2003

  - job_name: "node"
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080