export { default as BotikIcon } from "./src/Botik.svelte"
export { default as BotsIcon } from "./src/Bots.svelte"
export { default as HumansIcon } from "./src/Humans.svelte"
export { default as GroupsIcon } from "./src/Groups.svelte"
export { default as SettingsIcon } from "./src/Settings.svelte"
export { default as LoginIcon } from "./src/Login.svelte"
export { default as SidebarCloseIcon } from "./src/SidebarClose.svelte"

export { default as VisibleIcon } from "./src/Visible.svelte"
export { default as NotVisibleIcon } from "./src/NotVisible.svelte"
export { default as CloseIcon } from "./src/Close.svelte"